from global_vars import SAMPLE_RATE

SINGLES_RING_OUT_START = 0
SINGLES_RING_OUT_END = int(95.5 * SAMPLE_RATE)

POWER_CHORDS_RING_OUT_START = int(95.5 * SAMPLE_RATE)
POWER_CHORDS_RING_OUT_END = 144 * SAMPLE_RATE

PALM_MUTING_START = 144 * SAMPLE_RATE
PALM_MUTING_END = int(194.25 * SAMPLE_RATE)

CHORDS_ARPEGGIO_START = int(194.25 * SAMPLE_RATE)
CHORDS_ARPEGGIO_END = int(248.8 * SAMPLE_RATE)

CHORDS_STRUMMED_START = int(248.8 * SAMPLE_RATE)
CHORDS_STRUMMED_END = int(295.375 * SAMPLE_RATE)

PENTATONIC_SLOW_START = int(295.375 * SAMPLE_RATE)
PENTATONIC_SLOW_END = 345 * SAMPLE_RATE

PENTATONIC_FAST_START = 345 * SAMPLE_RATE
PENTATONIC_FAST_END = int(370.3 * SAMPLE_RATE)

TAPPING_START = int(370.3 * SAMPLE_RATE)
TAPPING_END = 396 * SAMPLE_RATE

TREMOLO_START = 396 * SAMPLE_RATE
TREMOLO_END = 454 * SAMPLE_RATE

NATURAL_HARMONICS_START = 454 * SAMPLE_RATE
NATURAL_HARMONICS_END = 501 * SAMPLE_RATE
